Scala Workshop
==============
:corpname: Lunatech Labs
Bart Schuller <schuller@lunatech.com>
v. 0.1, 2011-08-04

== What

My slides for a Scala Workshop for beginners. Just read the html or the pdf
and explore the source.

Ignore the stuff below, it's incomplete (install slidy2 backend in asciidoc).

== Tools needed

asciidoc::
  * on a Mac: `brew install asciidoc`
  * Probably available in your Linux distribution too
source-highlight::
  * `brew install source-highlight`
  * `apt-get install source-highlight`
docbook::
  Only needed for handouts
  * Mac: `brew install docbook`
  * Linux: it's probably a dependency of asciidoc, otherwise, get both
    the docbook dtds and the XSL toolchain
dblatex::
  Only needed for handouts. Needs a TeX installation, which eats a couple of
  Gb of disk space.
  * Mac: first install http://www.tug.org/mactex/[MacTeX], then install dblatex using
    https://github.com/bartschuller/homebrew/blob/master/Library/Formula/dblatex.rb
  * Linux: probably packaged

== Running

=== Creating the HTML presentation

`asciidoc -b slidy2 mypresentation.asciidoc`

Add `-v` if you encounter problems.

=== Creating the handout PDF

`a2x mypresentation.asciidoc`

Add `-v` if you encounter problems.

